### ISSUE TITLE
Advance Runner function bug when invoking function

### ISSUE THREAD

**Issue by sammyrTX** [sammyrTX/Python-Baseball_Project#9]
When there is a "hit" and the advance runner function is called, instead of a dictionary of just the bases, there is a tuple that apparently includes extraneous values from the calling function.
See traceback info below. Assign to myself since I broke it.

Hit! A Double
Traceback (most recent call last):
  File "Baseball_Proj_Main.py", line 64, in <module>
    ) = inning_process(inning_process_data)
  File "/Users/photos-field/Documents/__Python_Pycharm/PROJECTS/baseball_project_new_local/Python-Baseball_Project/baseball_functions.py", line 643, in inning_process
    score_list,) = at_bat(inning_data)
  File "/Users/photos-field/Documents/__Python_Pycharm/PROJECTS/baseball_project_new_local/Python-Baseball_Project/baseball_functions.py", line 472, in at_bat
    bb_diamond_fa,
  File "/Users/photos-field/Documents/__Python_Pycharm/PROJECTS/baseball_project_new_local/Python-Baseball_Project/baseball_functions.py", line 279, in process_pitch_result
    bb_diamond_f)
  File "/Users/photos-field/Documents/__Python_Pycharm/PROJECTS/baseball_project_new_local/Python-Baseball_Project/baseball_functions.py", line 134, in advance_runner
    home_plate_f, base1_f, base2_f, base3_f = bb_diamond_adv_runner.values()
AttributeError: 'tuple' object has no attribute 'values'

**Comment by sammyrTX** [comment]
# FIXED
Calling function (at_bat) did not properly unpack data from call to process_pitch_result. Fixed error in recent commit. Main now runs to completion.
